# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: swift

cache: cocoapods
podfile: Example/Podfile
xcode_sdk: iphonesimulator

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- xcodebuild -workspace Example/Demo.xcworkspace -scheme Demo
- pod lib lint
